### ISSUE TITLE
Stworzyć klasy odpowiadające strukturze bazodanowej

### ISSUE THREAD

**Issue by michal-marciniec** [mateusz-siwiec/fifa-stats#3]
### Dependent on / Zależne od
Dopiero po wykonaniu #2 

### Description / Opis
Stwórz klasy odpowiadające tabelom w bazie danych. Niech każda ma takie pola jak kolumny tej tabeli.

**Comment by michal-marciniec** [comment]
Kilka poprawek do zrobienia :)

https://github.com/mateusz-siwiec/fifa-stats/commit/7412887b3c8ea680ee3582e046472f33a813c472

**Comment by mateusz-siwiec** [comment]
@michal-marciniec , teraz jest dobrze?

**Comment by michal-marciniec** [comment]
@mateusz-siwiec jeszcze brakuje zmiany nazwy klasy (na dużą literę) dla gracza i drużyny

**Comment by michal-marciniec** [comment]
jest OK
