### ISSUE TITLE
Podstawowa wersja interfejsu

### ISSUE THREAD

**Issue by michal-marciniec** [mateusz-siwiec/fifa-stats#4]
### Dependent on / Zależne od
Dopiero po wykonaniu #2 

### Opis
Stworzyć podstawowy interfejs do wprowadzania wyniku. Składający się z pola imienia i wyniku dla gospodarza, identycznie dla gościa oraz przycisk "OK".
Mniej więcej coś w stylu:
![image](https://user-images.githubusercontent.com/17987592/32726942-15b39dbc-c87b-11e7-88ed-4fbbb092c52d.png)
(oczywiście wg własnej inwencji).

Po kliknięciu "OK" powinny się wypisać wszystkie wprowadzone informacje.
Np. "Gospodarz: JANUSZ - 1, Gość: JAN - 2".
Na razie nie ma co się przejmować tym co będzie jak użytkownik poda puste pole, albo wpisze tekst zamiast liczby, załóżmy na razie, że użytkownicy są mili ;)

**Comment by mateusz-siwiec** [comment]
@michal-marciniec może być tak zrobione?

**Comment by michal-marciniec** [comment]
Jasne, interfejs wygląda super. A udało Ci się podpiąć akcję pod przycisk żeby wypisywało wartości z pól tekstowych?

**Comment by mateusz-siwiec** [comment]
Aaa o tym zapomniałem.. :/

**Comment by michal-marciniec** [comment]
To jeszcze z tym się pobaw :)

**Comment by michal-marciniec** [comment]
done
