### ISSUE TITLE
Rozbić klasę Mecz

### ISSUE THREAD

**Issue by michal-marciniec** [mateusz-siwiec/fifa-stats#7]
Już mamy trochę pól w klasie Mecz i w zasadzie pola gospodarza i gościa są...dość podobne, możemy spróbować to trochę rozbić żeby się nie powtarzać :) A można to zrobić następująco:

Tworzymy klasę WynikGracza, które będzie miał pola graczId, druzynaId i liczbaBramek.

A w klasie Mecz poszczególne pola będzie można zamienić przez dwa pola typu WynikGracza: wynikGospodarza i wynikGoscia

P.S. Przy okazji, zmień `Id` na `id`.

**Comment by mateusz-siwiec** [comment]
@michal-marciniec , do sprawdzenia

**Comment by michal-marciniec** [comment]
done
